# Generated by Django 5.0.3 on 2024-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Projects'},
        ),
    ]
